#on:
 # push:
  #  branches: [ main ]
#jobs:
  #build:
   # runs-on: ubuntu-latest
    #steps:
     # - uses: actions/checkout@v3
      #- name: Set up Node.js
       # uses: actions/setup-node@v3
        #with:
         # node-version: '18'
      #- run: npm install
      #- run: npm test 
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies and run tests
      - run: npm install
      - run: npm test

  docker-build:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job only runs after the 'build' job
    steps:
      - uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        id: docker-build-push
        uses: cloudposse/github-action-docker-build-push@main
        with:
          registry: registry.hub.docker.com
          organization: "${{ github.repository_owner }}"
          repository: "${{ github.event.repository.name }}"
          login: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.sha }}  # Use commit SHA as the tag

    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      tag: ${{ steps.docker-build-push.outputs.tag }}



